# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('ip_address', models.GenericIPAddressField()),
                ('transaction_id', models.CharField(blank=True, max_length=30)),
                ('exchange_amount', models.CharField(blank=True, max_length=30)),
                ('from_currency', models.CharField(blank=True, max_length=30)),
                ('to_currency', models.CharField(blank=True, max_length=30)),
                ('result_amount', models.CharField(blank=True, max_length=30)),
                ('confirmed', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
