# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('qr', models.ImageField(upload_to='')),
            ],
        ),
    ]
