# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='qr',
        ),
    ]
